In [102]:
# 导入相应的包
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.svm import LinearSVC

from training1 import training


In [103]:
?training

In [104]:
# 使用sklearn自带的鸢尾花数据
iris_dataset = load_iris()
x = iris_dataset["data"]
y = iris_dataset["target"]
x = x[y!=2,:]
y = y[y!=2]

In [95]:
# 拆分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)
print(np.shape(y_train))
print(np.shape(X_train))

(75,)
(75, 4)


In [105]:
#%% 开始机器学习：自己手动实现
alpha = 0.1 # 学习率，每一步走多远
max_cycles = 1000 # 最大循环次数
w_fit =  np.array([0, 0, 0, 0]) # 初始化回归系数w
n_sample = np.shape(y_train)[0]
# 迭代100次，走100步看看能否到达山脚下
for index in range(max_cycles):
    z = np.dot(X_train,w_fit)  # 矩阵乘法
    yhat = 1.0/(1+np.exp(-z))   # 计算预测的y 
    loss = (-1/n_sample)*(np.sum((y_train*np.log(yhat)) + ((1-y_train)*(np.log(1-yhat)))))  # 损失函数
    delta_loss = (1/n_sample)*(np.dot(X_train.T, (yhat-y_train).T)) # 当前loss在w上的导数， 即对w求导
#     print(f"{index}:loss={loss:.5f}, w_fit={w_fit}")
    w_fit = w_fit - alpha * delta_loss.T  # 更新w_fit

# print(f"拟合出的权重为{w_fit}")

In [106]:
w_fit = training(X_train, y_train)

NameError: name 'np' is not defined

In [79]:
print(w_fit)

[-0.61665101 -1.97659628  3.06825799  1.36511966]


In [80]:
# 对测试集进行测试
z = np.dot(X_test, w_fit)  # 矩阵乘法
yhat = 1.0/(1+np.exp(-z))   # 计算预测的y 
yhat = np.int64(yhat>0.5)  # 预测概率大于0.5视为正类（versicolor），小于0.5为负类（setosa）
acc = np.sum((yhat - y_test)==0)/len(yhat)  # 计算准确度，即分类正确比例
# print((yhat - y_test))
# print((yhat - y_test)==0)
print(acc)

1.0


In [24]:
(1-1) == 0.4

False

In [67]:
#%%  使用sklearn封装的逻辑回归
lr = LinearSVC()
lr.fit(X_train, y_train)
yhat = lr.predict(X_test)
acc = np.sum((yhat - y_test)==0)/len(yhat)
print(yhat > 0.8)
print(np.int64(yhat > 0.8))
print(y_test)

[False  True False  True  True  True False  True  True  True  True  True
  True False False False False False False False False  True False  True
 False]
[0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0]
[0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0]


In [68]:
?LinearSVC

In [39]:
a = [1,2,3]

In [42]:
a[0:2]

[1, 2]

In [45]:
np.exp(-100)

3.720075976020836e-44